package com.data3000.data3000lib.bd;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CrgCargo generated by hbm2java
 */
public class CrgCargo implements java.io.Serializable {

	private long crgIdn;
	private String crgNombre;
	private String crgDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DpnCrgUsuario> dpnCrgUsuarios = new HashSet<DpnCrgUsuario>(0);

	public CrgCargo() {
	}

	public CrgCargo(long crgIdn, String crgNombre, String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.crgIdn = crgIdn;
		this.crgNombre = crgNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public CrgCargo(long crgIdn, String crgNombre, String crgDescripcion, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum, Set<DpnCrgUsuario> dpnCrgUsuarios) {
		this.crgIdn = crgIdn;
		this.crgNombre = crgNombre;
		this.crgDescripcion = crgDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.dpnCrgUsuarios = dpnCrgUsuarios;
	}

	public long getCrgIdn() {
		return this.crgIdn;
	}

	public void setCrgIdn(long crgIdn) {
		this.crgIdn = crgIdn;
	}

	public String getCrgNombre() {
		return this.crgNombre;
	}

	public void setCrgNombre(String crgNombre) {
		this.crgNombre = crgNombre;
	}

	public String getCrgDescripcion() {
		return this.crgDescripcion;
	}

	public void setCrgDescripcion(String crgDescripcion) {
		this.crgDescripcion = crgDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DpnCrgUsuario> getDpnCrgUsuarios() {
		return this.dpnCrgUsuarios;
	}

	public void setDpnCrgUsuarios(Set<DpnCrgUsuario> dpnCrgUsuarios) {
		this.dpnCrgUsuarios = dpnCrgUsuarios;
	}

}
