package com.data3000.data3000lib.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.data3000.admin.ant.Columna;
import com.data3000.admin.ant.Tabla;

/**
 * DocArchivoVersion generated by hbm2java
 */
@Tabla
public class DocArchivoVersion implements java.io.Serializable {

	private long archVersIdn;
	private DocArchivo docArchivo;
	
	@Columna(orden=1, aplica={"form.1008"})
	private String archVersTag;
	
	private String archVersRuta;
	private String archVersChecksum;
	
	
	private String archVersDescripcion;
	
	@Columna(orden=3, aplica={"form.1008"})
	private String audiUsuario;
	
	@Columna(orden=4, aplica={"form.1008"})
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DocCampArch> docCampArches = new HashSet<DocCampArch>(0);
	
	private DocArchivoVersion docArchivoVersion;
	
	@Columna(orden=2, aplica={"form.1019"})
	private String nombreArchivo;

	public DocArchivoVersion() {
	}

	public DocArchivoVersion(long archVersIdn, DocArchivo docArchivo, String archVersTag, String archVersRuta,
			String archVersChecksum, String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.archVersIdn = archVersIdn;
		this.docArchivo = docArchivo;
		this.archVersTag = archVersTag;
		this.archVersRuta = archVersRuta;
		extraerNombreArchivo(archVersRuta);
		this.archVersChecksum = archVersChecksum;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocArchivoVersion(long archVersIdn, DocArchivo docArchivo, String archVersTag, String archVersRuta,
			String archVersChecksum, String archVersDescripcion, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum, Set<DocCampArch> docCampArches, DocArchivoVersion docArchivoVersion) {
		this.archVersIdn = archVersIdn;
		this.docArchivo = docArchivo;
		this.archVersTag = archVersTag;
		this.archVersRuta = archVersRuta;
		extraerNombreArchivo(archVersRuta);
		this.archVersChecksum = archVersChecksum;
		this.archVersDescripcion = archVersDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.docCampArches = docCampArches;
		this.docArchivoVersion = docArchivoVersion;
	}
	
	public long getArchVersIdn() {
		return this.archVersIdn;
	}

	public void setArchVersIdn(long archVersIdn) {
		this.archVersIdn = archVersIdn;
	}

	public DocArchivo getDocArchivo() {
		return this.docArchivo;
	}

	public void setDocArchivo(DocArchivo docArchivo) {
		this.docArchivo = docArchivo;
	}

	public String getArchVersTag() {
		return this.archVersTag;
	}

	public void setArchVersTag(String archVersTag) {
		this.archVersTag = archVersTag;
	}

	public String getArchVersRuta() {
		return this.archVersRuta;
	}

	public void setArchVersRuta(String archVersRuta) {
		this.archVersRuta = archVersRuta;
		extraerNombreArchivo(archVersRuta);
	}

	public String getArchVersChecksum() {
		return this.archVersChecksum;
	}

	public void setArchVersChecksum(String archVersChecksum) {
		this.archVersChecksum = archVersChecksum;
	}

	public String getArchVersDescripcion() {
		return this.archVersDescripcion;
	}

	public void setArchVersDescripcion(String archVersDescripcion) {
		this.archVersDescripcion = archVersDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DocCampArch> getDocCampArches() {
		return this.docCampArches;
	}

	public void setDocCampArches(Set<DocCampArch> docCampArches) {
		this.docCampArches = docCampArches;
	}

	public DocArchivoVersion getDocArchivoVersion() {
		return docArchivoVersion;
	}

	public void setDocArchivoVersion(DocArchivoVersion docArchivoVersion) {
		this.docArchivoVersion = docArchivoVersion;
	}

	public String getNombreArchivo() {
		return nombreArchivo;
	}

	public void setNombreArchivo(String nombreArchivo) {
		this.nombreArchivo = nombreArchivo;
	}
	
	private void extraerNombreArchivo(String ruta){
		Path path = Paths.get(ruta);
		
		setNombreArchivo(path.getFileName().toString());
		
	}

}
