package com.data3000.data3000lib.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.ResourceBundle;
import java.util.Set;

import com.data3000.admin.ant.Columna;
import com.data3000.admin.ant.Tabla;
import com.data3000.admin.bd.PltUsuario;
import com.data3000.admin.utl.CampoTabla;
import com.data3000.admin.utl.ConstantesAdmin;

/**
 * DocArchivo generated by hbm2java
 */
@Tabla
public class DocArchivo implements java.io.Serializable {
	
	@Columna(orden = 1)
	private long archIdn;
	private DocSerieDoc docSerieDoc;
	private PltUsuario pltUsuario;
	private DocSistArch docSistArch;
	
	@Columna(orden = 2)
	private String archNombre;
	
	@Columna(orden = 3)
	private String archDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	
	@Columna(orden = 4)
	private boolean audiSiAnul;
	
	@Columna(orden = 5)
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DocAcl> docAcls = new HashSet<DocAcl>(0);
	private Set<DocArchivoVersion> docArchivoVersions = new HashSet<DocArchivoVersion>(0);

	public DocArchivo() {
	}

	public DocArchivo(long archIdn, DocSerieDoc docSerieDoc, PltUsuario pltUsuario, DocSistArch docSistArch,
			String archNombre, String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.archIdn = archIdn;
		this.docSerieDoc = docSerieDoc;
		this.pltUsuario = pltUsuario;
		this.docSistArch = docSistArch;
		this.archNombre = archNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocArchivo(long archIdn, DocSerieDoc docSerieDoc, PltUsuario pltUsuario, DocSistArch docSistArch,
			String archNombre, String archDescripcion, String audiUsuario, Date audiFechModi, boolean audiSiAnul,
			String audiMotiAnul, String audiChecksum, Set<DocAcl> docAcls, Set<DocArchivoVersion> docArchivoVersions) {
		this.archIdn = archIdn;
		this.docSerieDoc = docSerieDoc;
		this.pltUsuario = pltUsuario;
		this.docSistArch = docSistArch;
		this.archNombre = archNombre;
		this.archDescripcion = archDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.docAcls = docAcls;
		this.docArchivoVersions = docArchivoVersions;
	}

	public long getArchIdn() {
		return this.archIdn;
	}

	public void setArchIdn(long archIdn) {
		this.archIdn = archIdn;
	}

	public DocSerieDoc getDocSerieDoc() {
		return this.docSerieDoc;
	}

	public void setDocSerieDoc(DocSerieDoc docSerieDoc) {
		this.docSerieDoc = docSerieDoc;
	}

	public PltUsuario getPltUsuario() {
		return this.pltUsuario;
	}

	public void setPltUsuario(PltUsuario pltUsuario) {
		this.pltUsuario = pltUsuario;
	}

	public DocSistArch getDocSistArch() {
		return this.docSistArch;
	}

	public void setDocSistArch(DocSistArch docSistArch) {
		this.docSistArch = docSistArch;
	}

	public String getArchNombre() {
		return this.archNombre;
	}

	public void setArchNombre(String archNombre) {
		this.archNombre = archNombre;
	}

	public String getArchDescripcion() {
		return this.archDescripcion;
	}

	public void setArchDescripcion(String archDescripcion) {
		this.archDescripcion = archDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DocAcl> getDocAcls() {
		return this.docAcls;
	}

	public void setDocAcls(Set<DocAcl> docAcls) {
		this.docAcls = docAcls;
	}

	public Set<DocArchivoVersion> getDocArchivoVersions() {
		return this.docArchivoVersions;
	}

	public void setDocArchivoVersions(Set<DocArchivoVersion> docArchivoVersions) {
		this.docArchivoVersions = docArchivoVersions;
	}
	
	

}
