package com.data3000.data3000lib.bd;

// Generated 24/07/2014 10:02:48 PM by Hibernate Tools 3.4.0.CR1


import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.ResourceBundle;
import java.util.Set;

import com.data3000.admin.bd.PltRol;
import com.data3000.admin.bd.PltUsuaRol;
import com.data3000.admin.bd.PltUsuario;
import com.data3000.admin.utl.CampoTabla;
import com.data3000.admin.utl.ConstantesAdmin;
import com.data3000.admin.vo.RegistroTabla;
import com.data3000.admin.vo.Usuario;

/**
 * DocArchivo generated by hbm2java
 */
public class DocArchivo extends RegistroTabla implements java.io.Serializable {

	private long archIdn;
	private DocTipoArchivo docTipoArchivo;
	private PltUsuario pltUsuario;
	private DocSistArch docSistArch;
	private String archNombre;
	private String archDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DocArchivoVersion> docArchivoVersions = new HashSet<DocArchivoVersion>(
			0);
	private Set<DocAcl> docAcls = new HashSet<DocAcl>(0);
	
	
	
	public static List<CampoTabla> getCamposTabla() {
		
		ResourceBundle resource = ResourceBundle.getBundle("com.data3000.data3000lib.bd.DocArchivoCampos");
		String valor = resource.getString(ConstantesAdmin.NOMBRE_CLAVE_CAMPOS_MOSTRAR_TABLA);
		String[] camposMostrar = valor.split(",");

		List<CampoTabla> camposTabla = new ArrayList<CampoTabla>();
		for(String campoMostrar : camposMostrar) {
			CampoTabla campo = new CampoTabla(campoMostrar);
			camposTabla.add(campo);
		}		
		
		return camposTabla;
	}
	

	public DocArchivo() {
	}

	public DocArchivo(long archIdn, DocTipoArchivo docTipoArchivo,
			PltUsuario pltUsuario, DocSistArch docSistArch, String archNombre,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.archIdn = archIdn;
		this.docTipoArchivo = docTipoArchivo;
		this.pltUsuario = pltUsuario;
		this.docSistArch = docSistArch;
		this.archNombre = archNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocArchivo(long archIdn, DocTipoArchivo docTipoArchivo,
			PltUsuario pltUsuario, DocSistArch docSistArch, String archNombre,
			String archDescripcion, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum,
			Set<DocArchivoVersion> docArchivoVersions, Set<DocAcl> docAcls) {
		this.archIdn = archIdn;
		this.docTipoArchivo = docTipoArchivo;
		this.pltUsuario = pltUsuario;
		this.docSistArch = docSistArch;
		this.archNombre = archNombre;
		this.archDescripcion = archDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.docArchivoVersions = docArchivoVersions;
		this.docAcls = docAcls;
	}

	public long getArchIdn() {
		return this.archIdn;
	}

	public void setArchIdn(long archIdn) {
		this.archIdn = archIdn;
	}

	public DocTipoArchivo getDocTipoArchivo() {
		return this.docTipoArchivo;
	}

	public void setDocTipoArchivo(DocTipoArchivo docTipoArchivo) {
		this.docTipoArchivo = docTipoArchivo;
	}

	public DocSistArch getDocSistArch() {
		return this.docSistArch;
	}

	public void setDocSistArch(DocSistArch docSistArch) {
		this.docSistArch = docSistArch;
	}

	public String getArchNombre() {
		return this.archNombre;
	}

	public void setArchNombre(String archNombre) {
		this.archNombre = archNombre;
	}

	public String getArchDescripcion() {
		return this.archDescripcion;
	}

	public void setArchDescripcion(String archDescripcion) {
		this.archDescripcion = archDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DocArchivoVersion> getDocArchivoVersions() {
		return this.docArchivoVersions;
	}

	public void setDocArchivoVersions(Set<DocArchivoVersion> docArchivoVersions) {
		this.docArchivoVersions = docArchivoVersions;
	}
	
	
	public PltUsuario getPltUsuario() {
		return pltUsuario;
	}

	public void setPltUsuario(PltUsuario pltUsuario) {
		this.pltUsuario = pltUsuario;
	}

	public Set<DocAcl> getDocAcls() {
		return docAcls;
	}

	public void setDocAcls(Set<DocAcl> docAcls) {
		this.docAcls = docAcls;
	}
	
	
	@Override
	public boolean siMostrarSegunUsuario(Usuario usuario){
		
		PltUsuario pltUsuario = (PltUsuario) usuario;
		
		if(getPltUsuario().getUsuaIdn() == pltUsuario.getUsuaIdn()){
			return true;
		} else {
			Set<DocAcl> permisos = getDocAcls();
			for(DocAcl permiso : permisos){
				PltUsuario usuarioPermiso = permiso.getPltUsuario();
				PltRol rolPermiso = permiso.getPltRol();
				if(usuarioPermiso != null && usuarioPermiso.getUsuaIdn() == pltUsuario.getUsuaIdn()){
					if(permiso.isAclSiLectura()){
						return true;
					} else {
						return false;
					}
				} else if(rolPermiso != null){
					
					Set<PltUsuaRol> roles = pltUsuario.getPltUsuaRols();
					boolean encontro = false;
					for(PltUsuaRol usuarioRol : roles){
						if(rolPermiso.getRolIdn() == usuarioRol.getPltRol().getRolIdn() && permiso.isAclSiLectura()){
							return true;
						}
					}
				}
			}
		}
		
		return false;
		
	}
	
	

}
