package com.data3000.data3000lib.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import com.data3000.admin.ant.Columna;
import com.data3000.admin.ant.Tabla;

/**
 * DocCampTipo generated by hbm2java
 */
@Tabla
public class DocCampTipo implements java.io.Serializable {

	private long campTipoIdn;
	private DocSerieDoc docSerieDoc;
	
	@Columna(orden=1)
	private DocCampo docCampo;
	
	@Columna(orden=2)
	private boolean campTipoRequerido;
	
	@Columna(orden=3)
	private short campTipoOrden;
	
	@Columna(orden=4)
	private String audiUsuario;
	
	@Columna(orden=5)
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;

	public DocCampTipo() {
	}

	public DocCampTipo(long campTipoIdn, DocSerieDoc docSerieDoc, DocCampo docCampo, boolean campTipoRequerido,
			short campTipoOrden, String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.campTipoIdn = campTipoIdn;
		this.docSerieDoc = docSerieDoc;
		this.docCampo = docCampo;
		this.campTipoRequerido = campTipoRequerido;
		this.campTipoOrden = campTipoOrden;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocCampTipo(long campTipoIdn, DocSerieDoc docSerieDoc, DocCampo docCampo, boolean campTipoRequerido,
			short campTipoOrden, String audiUsuario, Date audiFechModi, boolean audiSiAnul, String audiMotiAnul,
			String audiChecksum) {
		this.campTipoIdn = campTipoIdn;
		this.docSerieDoc = docSerieDoc;
		this.docCampo = docCampo;
		this.campTipoRequerido = campTipoRequerido;
		this.campTipoOrden = campTipoOrden;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
	}

	public long getCampTipoIdn() {
		return this.campTipoIdn;
	}

	public void setCampTipoIdn(long campTipoIdn) {
		this.campTipoIdn = campTipoIdn;
	}

	public DocSerieDoc getDocSerieDoc() {
		return this.docSerieDoc;
	}

	public void setDocSerieDoc(DocSerieDoc docSerieDoc) {
		this.docSerieDoc = docSerieDoc;
	}

	public DocCampo getDocCampo() {
		return this.docCampo;
	}

	public void setDocCampo(DocCampo docCampo) {
		this.docCampo = docCampo;
	}

	public boolean isCampTipoRequerido() {
		return this.campTipoRequerido;
	}

	public void setCampTipoRequerido(boolean campTipoRequerido) {
		this.campTipoRequerido = campTipoRequerido;
	}

	public short getCampTipoOrden() {
		return this.campTipoOrden;
	}

	public void setCampTipoOrden(short campTipoOrden) {
		this.campTipoOrden = campTipoOrden;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	
}
