package com.data3000.data3000lib.bd;

// Generated 24/07/2014 10:02:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DocCampTipo generated by hbm2java
 */
public class DocCampTipo implements java.io.Serializable {

	private long campTipoIdn;
	private long campoIdn;
	private long tipoIdn;
	private boolean campTipoRequerido;
	private short campTipoOrden;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;

	public DocCampTipo() {
	}

	public DocCampTipo(long campTipoIdn, long campoIdn, long tipoIdn,
			boolean campTipoRequerido, short campTipoOrden, String audiUsuario,
			Date audiFechModi, boolean audiSiAnul) {
		this.campTipoIdn = campTipoIdn;
		this.campoIdn = campoIdn;
		this.tipoIdn = tipoIdn;
		this.campTipoRequerido = campTipoRequerido;
		this.campTipoOrden = campTipoOrden;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocCampTipo(long campTipoIdn, long campoIdn, long tipoIdn,
			boolean campTipoRequerido, short campTipoOrden, String audiUsuario,
			Date audiFechModi, boolean audiSiAnul, String audiMotiAnul,
			String audiChecksum) {
		this.campTipoIdn = campTipoIdn;
		this.campoIdn = campoIdn;
		this.tipoIdn = tipoIdn;
		this.campTipoRequerido = campTipoRequerido;
		this.campTipoOrden = campTipoOrden;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
	}

	public long getCampTipoIdn() {
		return this.campTipoIdn;
	}

	public void setCampTipoIdn(long campTipoIdn) {
		this.campTipoIdn = campTipoIdn;
	}

	public long getCampoIdn() {
		return this.campoIdn;
	}

	public void setCampoIdn(long campoIdn) {
		this.campoIdn = campoIdn;
	}

	public long getTipoIdn() {
		return this.tipoIdn;
	}

	public void setTipoIdn(long tipoIdn) {
		this.tipoIdn = tipoIdn;
	}

	public boolean isCampTipoRequerido() {
		return this.campTipoRequerido;
	}

	public void setCampTipoRequerido(boolean campTipoRequerido) {
		this.campTipoRequerido = campTipoRequerido;
	}

	public short getCampTipoOrden() {
		return this.campTipoOrden;
	}

	public void setCampTipoOrden(short campTipoOrden) {
		this.campTipoOrden = campTipoOrden;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

}
