package com.data3000.data3000lib.bd;

// Generated 27/07/2014 02:43:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DocCampTipo generated by hbm2java
 */
public class DocCampTipo implements java.io.Serializable {

	private long campTipoIdn;
	private DocTipoArchivo docTipoArchivo;
	private DocCampo docCampo;
	private boolean campTipoRequerido;
	private short campTipoOrden;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;

	public DocCampTipo() {
	}

	public DocCampTipo(long campTipoIdn, DocTipoArchivo docTipoArchivo,
			DocCampo docCampo, boolean campTipoRequerido, short campTipoOrden,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.campTipoIdn = campTipoIdn;
		this.docTipoArchivo = docTipoArchivo;
		this.docCampo = docCampo;
		this.campTipoRequerido = campTipoRequerido;
		this.campTipoOrden = campTipoOrden;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocCampTipo(long campTipoIdn, DocTipoArchivo docTipoArchivo,
			DocCampo docCampo, boolean campTipoRequerido, short campTipoOrden,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul,
			String audiMotiAnul, String audiChecksum) {
		this.campTipoIdn = campTipoIdn;
		this.docTipoArchivo = docTipoArchivo;
		this.docCampo = docCampo;
		this.campTipoRequerido = campTipoRequerido;
		this.campTipoOrden = campTipoOrden;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
	}

	public long getCampTipoIdn() {
		return this.campTipoIdn;
	}

	public void setCampTipoIdn(long campTipoIdn) {
		this.campTipoIdn = campTipoIdn;
	}

	public DocTipoArchivo getDocTipoArchivo() {
		return this.docTipoArchivo;
	}

	public void setDocTipoArchivo(DocTipoArchivo docTipoArchivo) {
		this.docTipoArchivo = docTipoArchivo;
	}

	public DocCampo getDocCampo() {
		return this.docCampo;
	}

	public void setDocCampo(DocCampo docCampo) {
		this.docCampo = docCampo;
	}

	public boolean isCampTipoRequerido() {
		return this.campTipoRequerido;
	}

	public void setCampTipoRequerido(boolean campTipoRequerido) {
		this.campTipoRequerido = campTipoRequerido;
	}

	public short getCampTipoOrden() {
		return this.campTipoOrden;
	}

	public void setCampTipoOrden(short campTipoOrden) {
		this.campTipoOrden = campTipoOrden;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

}
