package com.data3000.data3000lib.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocCampo generated by hbm2java
 */
public class DocCampo implements java.io.Serializable {

	private long campoIdn;
	private String campoNombre;
	private String campoDescripcion;
	private byte campoTipo;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DocCampTipo> docCampTipos = new HashSet<DocCampTipo>(0);
	private Set<DocCampArch> docCampArches = new HashSet<DocCampArch>(0);

	public DocCampo() {
	}

	public DocCampo(long campoIdn, String campoNombre, byte campoTipo, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul) {
		this.campoIdn = campoIdn;
		this.campoNombre = campoNombre;
		this.campoTipo = campoTipo;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocCampo(long campoIdn, String campoNombre, String campoDescripcion, byte campoTipo, String audiUsuario,
			Date audiFechModi, boolean audiSiAnul, String audiMotiAnul, String audiChecksum,
			Set<DocCampTipo> docCampTipos, Set<DocCampArch> docCampArches) {
		this.campoIdn = campoIdn;
		this.campoNombre = campoNombre;
		this.campoDescripcion = campoDescripcion;
		this.campoTipo = campoTipo;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.docCampTipos = docCampTipos;
		this.docCampArches = docCampArches;
	}

	public long getCampoIdn() {
		return this.campoIdn;
	}

	public void setCampoIdn(long campoIdn) {
		this.campoIdn = campoIdn;
	}

	public String getCampoNombre() {
		return this.campoNombre;
	}

	public void setCampoNombre(String campoNombre) {
		this.campoNombre = campoNombre;
	}

	public String getCampoDescripcion() {
		return this.campoDescripcion;
	}

	public void setCampoDescripcion(String campoDescripcion) {
		this.campoDescripcion = campoDescripcion;
	}

	public byte getCampoTipo() {
		return this.campoTipo;
	}

	public void setCampoTipo(byte campoTipo) {
		this.campoTipo = campoTipo;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DocCampTipo> getDocCampTipos() {
		return this.docCampTipos;
	}

	public void setDocCampTipos(Set<DocCampTipo> docCampTipos) {
		this.docCampTipos = docCampTipos;
	}

	public Set<DocCampArch> getDocCampArches() {
		return this.docCampArches;
	}

	public void setDocCampArches(Set<DocCampArch> docCampArches) {
		this.docCampArches = docCampArches;
	}
	
	@Override
	public String toString(){
		return getCampoNombre();
	}

}
