package com.data3000.data3000lib.bd;

// Generated 24/07/2014 10:02:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * DocCampo generated by hbm2java
 */
public class DocCampo implements java.io.Serializable {

	private long campoIdn;
	private String campoNombre;
	private String campoDescripcion;
	private boolean campoTipo;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;

	public DocCampo() {
	}

	public DocCampo(long campoIdn, String campoNombre, String campoDescripcion,
			boolean campoTipo, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul) {
		this.campoIdn = campoIdn;
		this.campoNombre = campoNombre;
		this.campoDescripcion = campoDescripcion;
		this.campoTipo = campoTipo;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocCampo(long campoIdn, String campoNombre, String campoDescripcion,
			boolean campoTipo, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum) {
		this.campoIdn = campoIdn;
		this.campoNombre = campoNombre;
		this.campoDescripcion = campoDescripcion;
		this.campoTipo = campoTipo;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
	}

	public long getCampoIdn() {
		return this.campoIdn;
	}

	public void setCampoIdn(long campoIdn) {
		this.campoIdn = campoIdn;
	}

	public String getCampoNombre() {
		return this.campoNombre;
	}

	public void setCampoNombre(String campoNombre) {
		this.campoNombre = campoNombre;
	}

	public String getCampoDescripcion() {
		return this.campoDescripcion;
	}

	public void setCampoDescripcion(String campoDescripcion) {
		this.campoDescripcion = campoDescripcion;
	}

	public boolean isCampoTipo() {
		return this.campoTipo;
	}

	public void setCampoTipo(boolean campoTipo) {
		this.campoTipo = campoTipo;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

}
