package com.data3000.data3000lib.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocSerieDoc generated by hbm2java
 */
public class DocSerieDoc implements java.io.Serializable {

	private long serieDocIdn;
	private DocSistArch docSistArch;
	private String serieDocNombre;
	private String serieDocDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Long serieDocPadre;
	private String serieDocTipo;
	private Set<DocCampTipo> docCampTipos = new HashSet<DocCampTipo>(0);
	private Set<DocArchivo> docArchivos = new HashSet<DocArchivo>(0);
	private Set<DocTipoAlma> docTipoAlmas = new HashSet<DocTipoAlma>(0);

	public DocSerieDoc() {
	}

	public DocSerieDoc(long serieDocIdn, String serieDocNombre, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul) {
		this.serieDocIdn = serieDocIdn;
		this.serieDocNombre = serieDocNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocSerieDoc(long serieDocIdn, DocSistArch docSistArch, String serieDocNombre, String serieDocDescripcion,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul, String audiMotiAnul, String audiChecksum,
			Long serieDocPadre, String serieDocTipo, Set<DocCampTipo> docCampTipos, Set<DocArchivo> docArchivos,
			Set<DocTipoAlma> docTipoAlmas) {
		this.serieDocIdn = serieDocIdn;
		this.docSistArch = docSistArch;
		this.serieDocNombre = serieDocNombre;
		this.serieDocDescripcion = serieDocDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.serieDocPadre = serieDocPadre;
		this.serieDocTipo = serieDocTipo;
		this.docCampTipos = docCampTipos;
		this.docArchivos = docArchivos;
		this.docTipoAlmas = docTipoAlmas;
	}

	public long getSerieDocIdn() {
		return this.serieDocIdn;
	}

	public void setSerieDocIdn(long serieDocIdn) {
		this.serieDocIdn = serieDocIdn;
	}

	public DocSistArch getDocSistArch() {
		return this.docSistArch;
	}

	public void setDocSistArch(DocSistArch docSistArch) {
		this.docSistArch = docSistArch;
	}

	public String getSerieDocNombre() {
		return this.serieDocNombre;
	}

	public void setSerieDocNombre(String serieDocNombre) {
		this.serieDocNombre = serieDocNombre;
	}

	public String getSerieDocDescripcion() {
		return this.serieDocDescripcion;
	}

	public void setSerieDocDescripcion(String serieDocDescripcion) {
		this.serieDocDescripcion = serieDocDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Long getSerieDocPadre() {
		return this.serieDocPadre;
	}

	public void setSerieDocPadre(Long serieDocPadre) {
		this.serieDocPadre = serieDocPadre;
	}

	public String getSerieDocTipo() {
		return this.serieDocTipo;
	}

	public void setSerieDocTipo(String serieDocTipo) {
		this.serieDocTipo = serieDocTipo;
	}

	public Set<DocCampTipo> getDocCampTipos() {
		return this.docCampTipos;
	}

	public void setDocCampTipos(Set<DocCampTipo> docCampTipos) {
		this.docCampTipos = docCampTipos;
	}

	public Set<DocArchivo> getDocArchivos() {
		return this.docArchivos;
	}

	public void setDocArchivos(Set<DocArchivo> docArchivos) {
		this.docArchivos = docArchivos;
	}

	public Set<DocTipoAlma> getDocTipoAlmas() {
		return this.docTipoAlmas;
	}

	public void setDocTipoAlmas(Set<DocTipoAlma> docTipoAlmas) {
		this.docTipoAlmas = docTipoAlmas;
	}

}
