package com.data3000.data3000lib.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.data3000.admin.bd.PltUsuario;

/**
 * DocSistArch generated by hbm2java
 */
public class DocSistArch implements java.io.Serializable {

	private long sistArchIdn;
	private DocSistArch docSistArch;
	private PltUsuario pltUsuario;
	private String sistArchNombre;
	private String sistArchDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private String sistArchTipo;
	private Set<DocSistArch> docSistArches = new HashSet<DocSistArch>(0);
	private Set<DocAcl> docAcls = new HashSet<DocAcl>(0);
	private Set<DocSerieDoc> docSerieDocs = new HashSet<DocSerieDoc>(0);
	private Set<DocArchivo> docArchivos = new HashSet<DocArchivo>(0);

	public DocSistArch() {
	}

	public DocSistArch(long sistArchIdn, PltUsuario pltUsuario, String sistArchNombre, String audiUsuario,
			Date audiFechModi, boolean audiSiAnul) {
		this.sistArchIdn = sistArchIdn;
		this.pltUsuario = pltUsuario;
		this.sistArchNombre = sistArchNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocSistArch(long sistArchIdn, DocSistArch docSistArch, PltUsuario pltUsuario, String sistArchNombre,
			String sistArchDescripcion, String audiUsuario, Date audiFechModi, boolean audiSiAnul, String audiMotiAnul,
			String audiChecksum, String sistArchTipo, Set<DocSistArch> docSistArches, Set<DocAcl> docAcls,
			Set<DocSerieDoc> docSerieDocs, Set<DocArchivo> docArchivos) {
		this.sistArchIdn = sistArchIdn;
		this.docSistArch = docSistArch;
		this.pltUsuario = pltUsuario;
		this.sistArchNombre = sistArchNombre;
		this.sistArchDescripcion = sistArchDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.sistArchTipo = sistArchTipo;
		this.docSistArches = docSistArches;
		this.docAcls = docAcls;
		this.docSerieDocs = docSerieDocs;
		this.docArchivos = docArchivos;
	}

	public long getSistArchIdn() {
		return this.sistArchIdn;
	}

	public void setSistArchIdn(long sistArchIdn) {
		this.sistArchIdn = sistArchIdn;
	}

	public DocSistArch getDocSistArch() {
		return this.docSistArch;
	}

	public void setDocSistArch(DocSistArch docSistArch) {
		this.docSistArch = docSistArch;
	}

	public PltUsuario getPltUsuario() {
		return this.pltUsuario;
	}

	public void setPltUsuario(PltUsuario pltUsuario) {
		this.pltUsuario = pltUsuario;
	}

	public String getSistArchNombre() {
		return this.sistArchNombre;
	}

	public void setSistArchNombre(String sistArchNombre) {
		this.sistArchNombre = sistArchNombre;
	}

	public String getSistArchDescripcion() {
		return this.sistArchDescripcion;
	}

	public void setSistArchDescripcion(String sistArchDescripcion) {
		this.sistArchDescripcion = sistArchDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public String getSistArchTipo() {
		return this.sistArchTipo;
	}

	public void setSistArchTipo(String sistArchTipo) {
		this.sistArchTipo = sistArchTipo;
	}

	public Set<DocSistArch> getDocSistArches() {
		return this.docSistArches;
	}

	public void setDocSistArches(Set<DocSistArch> docSistArches) {
		this.docSistArches = docSistArches;
	}

	public Set<DocAcl> getDocAcls() {
		return this.docAcls;
	}

	public void setDocAcls(Set<DocAcl> docAcls) {
		this.docAcls = docAcls;
	}

	public Set<DocSerieDoc> getDocSerieDocs() {
		return this.docSerieDocs;
	}

	public void setDocSerieDocs(Set<DocSerieDoc> docSerieDocs) {
		this.docSerieDocs = docSerieDocs;
	}

	public Set<DocArchivo> getDocArchivos() {
		return this.docArchivos;
	}

	public void setDocArchivos(Set<DocArchivo> docArchivos) {
		this.docArchivos = docArchivos;
	}

}
