package com.data3000.data3000lib.bd;

// Generated 29/04/2014 06:42:38 PM by Hibernate Tools 3.4.0.CR1





import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.data3000.admin.bd.PltUsuario;

/**
 * DocSistArch generated by hbm2java
 */
public class DocSistArch implements java.io.Serializable {

	private long sistArchIdn;
	private DocSistArch docSistArch;
	private PltUsuario pltUsuario;
	private String sistArchNombre;
	private String sistArchDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DocAcl> docAcls = new HashSet<DocAcl>(0);
	private Set<DocSistArch> docSistArchs = new HashSet<DocSistArch>(0);
	private Set<DocArchivo> docArchivos = new HashSet<DocArchivo>(0);

	public DocSistArch() {
	}

	public DocSistArch(long sistArchIdn, PltUsuario pltUsuario, String sistArchNombre,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.sistArchIdn = sistArchIdn;
		this.sistArchNombre = sistArchNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.pltUsuario = pltUsuario;
	}

	public DocSistArch(long sistArchIdn, DocSistArch docSistArch, PltUsuario pltUsuario,
			String sistArchNombre, String sistArchDescripcion,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul,
			String audiMotiAnul, String audiChecksum,
			Set<DocAcl> docAcls, Set<DocSistArch> docSistArchs, Set<DocArchivo> docArchivos) {
		this.sistArchIdn = sistArchIdn;
		this.docSistArch = docSistArch;
		this.sistArchNombre = sistArchNombre;
		this.sistArchDescripcion = sistArchDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.docSistArchs = docSistArchs;
		this.docArchivos = docArchivos;
		this.pltUsuario = pltUsuario;
		this.docAcls = docAcls;
	}

	public long getSistArchIdn() {
		return this.sistArchIdn;
	}

	public void setSistArchIdn(long sistArchIdn) {
		this.sistArchIdn = sistArchIdn;
	}

	public DocSistArch getDocSistArch() {
		return this.docSistArch;
	}

	public void setDocSistArch(DocSistArch docSistArch) {
		this.docSistArch = docSistArch;
	}

	public String getSistArchNombre() {
		return this.sistArchNombre;
	}

	public void setSistArchNombre(String sistArchNombre) {
		this.sistArchNombre = sistArchNombre;
	}

	public String getSistArchDescripcion() {
		return this.sistArchDescripcion;
	}

	public void setSistArchDescripcion(String sistArchDescripcion) {
		this.sistArchDescripcion = sistArchDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DocSistArch> getDocSistArchs() {
		return this.docSistArchs;
	}

	public void setDocSistArchs(Set<DocSistArch> docSistArchs) {
		this.docSistArchs = docSistArchs;
	}

	public Set<DocArchivo> getDocArchivos() {
		return this.docArchivos;
	}

	public void setDocArchivos(Set<DocArchivo> docArchivos) {
		this.docArchivos = docArchivos;
	}
	
	@Override
	public String toString(){
		return getSistArchNombre();
	}

	public PltUsuario getPltUsuario() {
		return pltUsuario;
	}

	public void setPltUsuario(PltUsuario pltUsuario) {
		this.pltUsuario = pltUsuario;
	}

	public Set<DocAcl> getDocAcls() {
		return docAcls;
	}

	public void setDocAcls(Set<DocAcl> docAcls) {
		this.docAcls = docAcls;
	}
	
	
	
}
