package com.data3000.data3000lib.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import com.data3000.admin.ant.Columna;
import com.data3000.admin.ant.Tabla;

/**
 * DocTipoAlma generated by hbm2java
 */
@Tabla
public class DocTipoAlma implements java.io.Serializable {

	private long tipoAlmaIdn;
	private DocSerieDoc docSerieDoc;
	@Columna(orden=1)
	private String tipoAlmaNombre;
	@Columna(orden=2)
	private String tipoAlmaDescripcion;
	@Columna(orden=3)
	private Short tipoAlmaEdad;
	@Columna(orden=4)
	private String tipoAlmaDispfinal;
	private String audiUsuario;
	private Date audiFechModi;
	private Boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;

	public DocTipoAlma() {
	}

	public DocTipoAlma(long tipoAlmaIdn, DocSerieDoc docSerieDoc, String tipoAlmaNombre, String audiUsuario,
			Date audiFechModi, String audiChecksum) {
		this.tipoAlmaIdn = tipoAlmaIdn;
		this.docSerieDoc = docSerieDoc;
		this.tipoAlmaNombre = tipoAlmaNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiChecksum = audiChecksum;
	}

	public DocTipoAlma(long tipoAlmaIdn, DocSerieDoc docSerieDoc, String tipoAlmaNombre, String tipoAlmaDescripcion,
			Short tipoAlmaEdad, String tipoAlmaDispfinal, String audiUsuario, Date audiFechModi, Boolean audiSiAnul,
			String audiMotiAnul, String audiChecksum) {
		this.tipoAlmaIdn = tipoAlmaIdn;
		this.docSerieDoc = docSerieDoc;
		this.tipoAlmaNombre = tipoAlmaNombre;
		this.tipoAlmaDescripcion = tipoAlmaDescripcion;
		this.tipoAlmaEdad = tipoAlmaEdad;
		this.tipoAlmaDispfinal = tipoAlmaDispfinal;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
	}

	public long getTipoAlmaIdn() {
		return this.tipoAlmaIdn;
	}

	public void setTipoAlmaIdn(long tipoAlmaIdn) {
		this.tipoAlmaIdn = tipoAlmaIdn;
	}

	public DocSerieDoc getDocSerieDoc() {
		return this.docSerieDoc;
	}

	public void setDocSerieDoc(DocSerieDoc docSerieDoc) {
		this.docSerieDoc = docSerieDoc;
	}

	public String getTipoAlmaNombre() {
		return this.tipoAlmaNombre;
	}

	public void setTipoAlmaNombre(String tipoAlmaNombre) {
		this.tipoAlmaNombre = tipoAlmaNombre;
	}

	public String getTipoAlmaDescripcion() {
		return this.tipoAlmaDescripcion;
	}

	public void setTipoAlmaDescripcion(String tipoAlmaDescripcion) {
		this.tipoAlmaDescripcion = tipoAlmaDescripcion;
	}

	public Short getTipoAlmaEdad() {
		return this.tipoAlmaEdad;
	}

	public void setTipoAlmaEdad(Short tipoAlmaEdad) {
		this.tipoAlmaEdad = tipoAlmaEdad;
	}

	public String getTipoAlmaDispfinal() {
		return this.tipoAlmaDispfinal;
	}

	public void setTipoAlmaDispfinal(String tipoAlmaDispfinal) {
		this.tipoAlmaDispfinal = tipoAlmaDispfinal;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public Boolean getAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(Boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

}
