package com.data3000.data3000lib.bd;

// Generated 24/07/2014 10:02:48 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DocTipoArchivo generated by hbm2java
 */
public class DocTipoArchivo implements java.io.Serializable {

	private long tipoArchIdn;
	private String tipoArchNombre;
	private String tipoArchDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DocArchivo> docArchivos = new HashSet<DocArchivo>(0);

	public DocTipoArchivo() {
	}

	public DocTipoArchivo(long tipoArchIdn, String tipoArchNombre,
			String tipoArchDescripcion, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul) {
		this.tipoArchIdn = tipoArchIdn;
		this.tipoArchNombre = tipoArchNombre;
		this.tipoArchDescripcion = tipoArchDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocTipoArchivo(long tipoArchIdn, String tipoArchNombre,
			String tipoArchDescripcion, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum,
			Set<DocArchivo> docArchivos) {
		this.tipoArchIdn = tipoArchIdn;
		this.tipoArchNombre = tipoArchNombre;
		this.tipoArchDescripcion = tipoArchDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.docArchivos = docArchivos;
	}

	public long getTipoArchIdn() {
		return this.tipoArchIdn;
	}

	public void setTipoArchIdn(long tipoArchIdn) {
		this.tipoArchIdn = tipoArchIdn;
	}

	public String getTipoArchNombre() {
		return this.tipoArchNombre;
	}

	public void setTipoArchNombre(String tipoArchNombre) {
		this.tipoArchNombre = tipoArchNombre;
	}

	public String getTipoArchDescripcion() {
		return this.tipoArchDescripcion;
	}

	public void setTipoArchDescripcion(String tipoArchDescripcion) {
		this.tipoArchDescripcion = tipoArchDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DocArchivo> getDocArchivos() {
		return this.docArchivos;
	}

	public void setDocArchivos(Set<DocArchivo> docArchivos) {
		this.docArchivos = docArchivos;
	}

}
