package com.data3000.data3000lib.bd;

// Generated 27/07/2014 02:43:01 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.ResourceBundle;
import java.util.Set;

import com.data3000.admin.utl.CampoTabla;
import com.data3000.admin.utl.ConstantesAdmin;
import com.data3000.admin.vo.RegistroTabla;


/**
 * DocTipoArchivo generated by hbm2java
 */
public class DocTipoArchivo extends RegistroTabla  implements java.io.Serializable {

	private long tipoArchIdn;
	private String tipoArchNombre;
	private String tipoArchDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DocArchivo> docArchivos = new HashSet<DocArchivo>(0);
	private Set<DocCampTipo> docCampTipos = new HashSet<DocCampTipo>(0);
	
	public static List<CampoTabla> getCamposTabla() {
		String[] camposMostrar = new String[]{"tipoArchNombre","tipoArchDescripcion","audiUsuario","audiFechModi"};

		List<CampoTabla> camposTabla = new ArrayList<CampoTabla>();
		for(String campoMostrar : camposMostrar) {
			CampoTabla campo = new CampoTabla(campoMostrar);
			camposTabla.add(campo);
		}

		return camposTabla;
	}

	public DocTipoArchivo() {
	}

	public DocTipoArchivo(long tipoArchIdn, String tipoArchNombre,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.tipoArchIdn = tipoArchIdn;
		this.tipoArchNombre = tipoArchNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DocTipoArchivo(long tipoArchIdn, String tipoArchNombre,
			String tipoArchDescripcion, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum,
			Set<DocArchivo> docArchivos, Set<DocCampTipo> docCampTipos) {
		this.tipoArchIdn = tipoArchIdn;
		this.tipoArchNombre = tipoArchNombre;
		this.tipoArchDescripcion = tipoArchDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.docArchivos = docArchivos;
		this.docCampTipos = docCampTipos;
	}

	public long getTipoArchIdn() {
		return this.tipoArchIdn;
	}

	public void setTipoArchIdn(long tipoArchIdn) {
		this.tipoArchIdn = tipoArchIdn;
	}

	public String getTipoArchNombre() {
		return this.tipoArchNombre;
	}

	public void setTipoArchNombre(String tipoArchNombre) {
		this.tipoArchNombre = tipoArchNombre;
	}

	public String getTipoArchDescripcion() {
		return this.tipoArchDescripcion;
	}

	public void setTipoArchDescripcion(String tipoArchDescripcion) {
		this.tipoArchDescripcion = tipoArchDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DocArchivo> getDocArchivos() {
		return this.docArchivos;
	}

	public void setDocArchivos(Set<DocArchivo> docArchivos) {
		this.docArchivos = docArchivos;
	}

	public Set<DocCampTipo> getDocCampTipos() {
		return this.docCampTipos;
	}

	public void setDocCampTipos(Set<DocCampTipo> docCampTipos) {
		this.docCampTipos = docCampTipos;
	}
	
	
	
}
