package com.data3000.data3000lib.bd;

import java.util.Date;

import com.data3000.admin.bd.PltUsuario;

/**
 * DpnCrgUsuario generated by hbm2java
 */
public class DpnCrgUsuario implements java.io.Serializable {

	private long dpnCrgIdn;
	private CrgCargo crgCargo;
	private DpnDependencia dpnDependencia;
	private PltUsuario pltUsuario;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;

	public DpnCrgUsuario() {
	}

	public DpnCrgUsuario(long dpnCrgIdn, DpnDependencia dpnDependencia, PltUsuario pltUsuario, String audiUsuario,
			Date audiFechModi, boolean audiSiAnul) {
		this.dpnCrgIdn = dpnCrgIdn;
		this.dpnDependencia = dpnDependencia;
		this.pltUsuario = pltUsuario;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public DpnCrgUsuario(long dpnCrgIdn, CrgCargo crgCargo, DpnDependencia dpnDependencia, PltUsuario pltUsuario,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul, String audiMotiAnul) {
		this.dpnCrgIdn = dpnCrgIdn;
		this.crgCargo = crgCargo;
		this.dpnDependencia = dpnDependencia;
		this.pltUsuario = pltUsuario;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
	}

	public long getDpnCrgIdn() {
		return this.dpnCrgIdn;
	}

	public void setDpnCrgIdn(long dpnCrgIdn) {
		this.dpnCrgIdn = dpnCrgIdn;
	}

	public CrgCargo getCrgCargo() {
		return this.crgCargo;
	}

	public void setCrgCargo(CrgCargo crgCargo) {
		this.crgCargo = crgCargo;
	}

	public DpnDependencia getDpnDependencia() {
		return this.dpnDependencia;
	}

	public void setDpnDependencia(DpnDependencia dpnDependencia) {
		this.dpnDependencia = dpnDependencia;
	}

	public PltUsuario getPltUsuario() {
		return this.pltUsuario;
	}

	public void setPltUsuario(PltUsuario pltUsuario) {
		this.pltUsuario = pltUsuario;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

}
