package com.data3000.data3000lib.bd;



import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DpnDependencia generated by hbm2java
 */
public class DpnDependencia implements java.io.Serializable {

	private long dpnIdn;
	private String dpnNombre;
	private String dpnDescripcion;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnu;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<DpnCrgUsuario> dpnCrgUsuarios = new HashSet<DpnCrgUsuario>(0);

	public DpnDependencia() {
	}

	public DpnDependencia(long dpnIdn, String dpnNombre, String audiUsuario, Date audiFechModi, boolean audiSiAnu) {
		this.dpnIdn = dpnIdn;
		this.dpnNombre = dpnNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnu = audiSiAnu;
	}

	public DpnDependencia(long dpnIdn, String dpnNombre, String dpnDescripcion, String audiUsuario, Date audiFechModi,
			boolean audiSiAnu, String audiMotiAnul, String audiChecksum, Set<DpnCrgUsuario> dpnCrgUsuarios) {
		this.dpnIdn = dpnIdn;
		this.dpnNombre = dpnNombre;
		this.dpnDescripcion = dpnDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnu = audiSiAnu;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.dpnCrgUsuarios = dpnCrgUsuarios;
	}

	public long getDpnIdn() {
		return this.dpnIdn;
	}

	public void setDpnIdn(long dpnIdn) {
		this.dpnIdn = dpnIdn;
	}

	public String getDpnNombre() {
		return this.dpnNombre;
	}

	public void setDpnNombre(String dpnNombre) {
		this.dpnNombre = dpnNombre;
	}

	public String getDpnDescripcion() {
		return this.dpnDescripcion;
	}

	public void setDpnDescripcion(String dpnDescripcion) {
		this.dpnDescripcion = dpnDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnu() {
		return this.audiSiAnu;
	}

	public void setAudiSiAnu(boolean audiSiAnu) {
		this.audiSiAnu = audiSiAnu;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<DpnCrgUsuario> getDpnCrgUsuarios() {
		return this.dpnCrgUsuarios;
	}

	public void setDpnCrgUsuarios(Set<DpnCrgUsuario> dpnCrgUsuarios) {
		this.dpnCrgUsuarios = dpnCrgUsuarios;
	}

}
